# Generated by Django 3.1.5 on 2021-01-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apart_info',
            fields=[
                ('Aapart', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dmaj_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dmaj', models.CharField(max_length=35)),
                ('Ddep', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Floor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lfloor', models.CharField(max_length=35)),
                ('Lapart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Floor_Aapart', to='common.apart_info')),
            ],
            options={
                'unique_together': {('Lfloor', 'Lapart')},
            },
        ),
        migrations.CreateModel(
            name='Room_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rroom', models.IntegerField()),
                ('Rlimit', models.IntegerField()),
                ('exists', models.IntegerField()),
                ('RFAinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room_Floor_Aapart', to='common.floor_info')),
            ],
            options={
                'unique_together': {('Rroom', 'RFAinfo')},
            },
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=35)),
                ('Ssex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('Aroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.room_info')),
                ('Dmaj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.dmaj_info')),
            ],
        ),
        migrations.CreateModel(
            name='Pprice_info',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=35)),
                ('Pprice', models.IntegerField()),
                ('Pnum', models.IntegerField()),
                ('Pintime', models.DateField()),
                ('Pouttime', models.DateField()),
                ('Aapart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.apart_info')),
            ],
        ),
        migrations.CreateModel(
            name='Outer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oname', models.CharField(max_length=35)),
                ('Osex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('Ocellphone', models.IntegerField(blank=True, null=True)),
                ('Ointime', models.DateField()),
                ('Oouttime', models.DateField(blank=True, null=True)),
                ('Ops', models.CharField(max_length=200)),
                ('Aapart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.apart_info')),
            ],
        ),
    ]
