# Generated by Django 3.1.5 on 2021-01-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor_info',
            name='Lapart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Floor_apart', to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='RFAinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Room_Floor_apart', to='common.floor_info'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room_info',
            unique_together=set(),
        ),
    ]
