# Generated by Django 3.1.5 on 2021-01-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210127_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor_info',
            name='Lfloor',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='Rroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
