# Generated by Django 3.1.5 on 2021-01-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210127_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_info',
            name='Rroom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Aroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.room_info'),
        ),
    ]
