# Generated by Django 3.1.5 on 2021-01-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210127_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer_info',
            name='Ocellphone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pouttime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
