# Generated by Django 3.1.5 on 2021-01-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20210127_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart_info',
            name='Aapart',
            field=models.CharField(db_column='公寓楼', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dmaj_info',
            name='Ddep',
            field=models.CharField(db_column='学院', max_length=35),
        ),
        migrations.AlterField(
            model_name='dmaj_info',
            name='Dmaj',
            field=models.CharField(db_column='专业', max_length=35),
        ),
        migrations.AlterField(
            model_name='floor_info',
            name='Lapart',
            field=models.ForeignKey(db_column='公寓楼', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Floor_apart', to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='floor_info',
            name='Lfloor',
            field=models.CharField(db_column='楼层', max_length=35),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Aapart',
            field=models.ForeignKey(db_column='公寓楼', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Ocellphone',
            field=models.IntegerField(db_column='联系方式'),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Ointime',
            field=models.DateField(db_column='来访时间'),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Oname',
            field=models.CharField(db_column='姓名', max_length=35),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Oouttime',
            field=models.DateField(blank=True, db_column='离开时间', null=True),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Ops',
            field=models.CharField(db_column='备注', max_length=200),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Osex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='性别', max_length=10),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Aapart',
            field=models.ForeignKey(db_column='所属公寓楼', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pintime',
            field=models.DateField(db_column='搬入时间'),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pname',
            field=models.CharField(db_column='财务名称', max_length=35),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pnum',
            field=models.IntegerField(db_column='财务数量'),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pouttime',
            field=models.DateField(blank=True, db_column='搬出时间', null=True),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pprice',
            field=models.IntegerField(db_column='财务价格'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='RFAinfo',
            field=models.ForeignKey(db_column='公寓楼', on_delete=django.db.models.deletion.CASCADE, related_name='Room_Floor_apart', to='common.floor_info'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='Rlimit',
            field=models.IntegerField(db_column='容纳人数'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='Rroom',
            field=models.IntegerField(db_column='寝室号'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='exists',
            field=models.IntegerField(db_column='现居人数'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Aroom',
            field=models.ForeignKey(blank=True, db_column='寝室号', default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.room_info'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Dmaj',
            field=models.ForeignKey(db_column='专业', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.dmaj_info'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Sclass',
            field=models.IntegerField(db_column='班级'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Sid',
            field=models.IntegerField(db_column='学号', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Sname',
            field=models.CharField(db_column='姓名', max_length=35),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Ssex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='性别', max_length=10),
        ),
    ]
