# Generated by Django 3.1.5 on 2021-01-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20210127_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart_info',
            name='Aapart',
            field=models.CharField(db_column='apartment', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dmaj_info',
            name='Ddep',
            field=models.CharField(db_column='college', max_length=35),
        ),
        migrations.AlterField(
            model_name='dmaj_info',
            name='Dmaj',
            field=models.CharField(db_column='mojor', max_length=35),
        ),
        migrations.AlterField(
            model_name='floor_info',
            name='Lapart',
            field=models.ForeignKey(db_column='apartment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Floor_apart', to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='floor_info',
            name='Lfloor',
            field=models.CharField(db_column='floor', max_length=35),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Aapart',
            field=models.ForeignKey(db_column='apartment', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Ocellphone',
            field=models.IntegerField(db_column='cellphone'),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Ointime',
            field=models.DateField(db_column='visiting time'),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Oname',
            field=models.CharField(db_column='name', max_length=35),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Oouttime',
            field=models.DateField(blank=True, db_column='departure time', null=True),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Ops',
            field=models.CharField(db_column='remarks', max_length=200),
        ),
        migrations.AlterField(
            model_name='outer_info',
            name='Osex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='sex', max_length=10),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Aapart',
            field=models.ForeignKey(db_column='apartment', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.apart_info'),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pintime',
            field=models.DateField(db_column='move in time'),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pname',
            field=models.CharField(db_column='financial name', max_length=35),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pnum',
            field=models.IntegerField(db_column='number'),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pouttime',
            field=models.DateField(blank=True, db_column='move out time', null=True),
        ),
        migrations.AlterField(
            model_name='pprice_info',
            name='Pprice',
            field=models.IntegerField(db_column='price'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='RFAinfo',
            field=models.ForeignKey(db_column='apartment', on_delete=django.db.models.deletion.CASCADE, related_name='Room_Floor_apart', to='common.floor_info'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='Rlimit',
            field=models.IntegerField(db_column='upper limit'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='Rroom',
            field=models.IntegerField(db_column='dormitory number'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='exists',
            field=models.IntegerField(db_column='current residents'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Aroom',
            field=models.ForeignKey(blank=True, db_column='dormitory number', default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.room_info'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Dmaj',
            field=models.ForeignKey(db_column='major', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.dmaj_info'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Sclass',
            field=models.IntegerField(db_column='class'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Sid',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Sname',
            field=models.CharField(db_column='nama', max_length=35),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Ssex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='sex', max_length=10),
        ),
    ]
