# Generated by Django 3.1.5 on 2021-01-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210127_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Aroom',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, to='common.room_info'),
        ),
    ]
